[package]
name = "pomodoro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.8.0"
rodio = { version = "0.17.1"}
tokio = { version = "1.28.2", features = ["full"] }
